// pages/classify/classify.js
Page({

    /**
     * 页面的初始数据
     */
    data: {
        active: 0,
        classifyMaleList:[
            {
                title:"玄幻",
                classify:[
                    {
                        title:'东方玄幻',
                        subCatId:8,
                        catId:21
                    },
                    {
                        title:'异世大陆',
                        subCatId:73,
                        catId:21
                    },
                    {
                        title:'王朝争霸',
                        subCatId:58,
                        catId:21
                    },
                    {
                        title:'高武世界',
                        subCatId:78,
                        catId:21
                    },
                ]
            },
            {
                title:"奇幻",
                classify:[
                    {
                        title:'现代魔法',
                        subCatId:38,
                        catId:1
                    },
                    {
                        title:'剑与魔法',
                        subCatId:62,
                        catId:1
                    },
                    {
                        title:'史诗奇幻',
                        subCatId:201,
                        catId:1
                    },
                    {
                        title:'黑暗幻想',
                        subCatId:202,
                        catId:1
                    },
                    {
                        title:'历史神话',
                        subCatId:20092,
                        catId:1
                    },
                    {
                        title:'另类幻想',
                        subCatId:20093,
                        catId:1
                    }
                ]
            },
            {
                title:"武侠",
                classify:[
                    {
                        title:'传统武侠',
                        subCatId:28,
                        catId:2
                    },
                    {
                        title:'武侠幻想',
                        subCatId:30,
                        catId:2
                    },
                    {
                        title:'国术无双',
                        subCatId:206,
                        catId:2
                    },
                    {
                        title:'古武未来',
                        subCatId:20099,
                        catId:2
                    },
                    {
                        title:'武侠同人',
                        subCatId:20100,
                        catId:2
                    }
                ]
            },
            {
                title:"仙侠",
                classify:[
                    {
                        title:'修真文明',
                        subCatId:18,
                        catId:22
                    },
                    {
                        title:'幻想修仙',
                        subCatId:44,
                        catId:22
                    },
                    {
                        title:'现代修仙',
                        subCatId:64,
                        catId:22
                    },
                    {
                        title:'神话修仙',
                        subCatId:207,
                        catId:22
                    },
                    {
                        title:'古典仙侠',
                        subCatId:20101,
                        catId:22
                    }
                ]
            },
            {
                title:"都市",
                classify:[
                    {
                        title:'爱情婚姻',
                        subCatId:6,
                        catId:4
                    },
                    {
                        title:'都市生活',
                        subCatId:12,
                        catId:4
                    },
                    {
                        title:'都市异能',
                        subCatId:16,
                        catId:4
                    },
                    {
                        title:'异术超能',
                        subCatId:74,
                        catId:4
                    },
                    {
                        title:'青春校园',
                        subCatId:130,
                        catId:4
                    },
                    {
                        title:'娱乐明星',
                        subCatId:151,
                        catId:4
                    },
                    {
                        title:'商战职场',
                        subCatId:153,
                        catId:4
                    },
                ]
            },
            {
                title:"现实",
                classify:[
                    {
                        title:'社会乡土',
                        subCatId:153,
                        catId:15
                    },
                    {
                        title:'生活时尚',
                        subCatId:153,
                        catId:15
                    },
                    {
                        title:'文学艺术',
                        subCatId:153,
                        catId:15
                    },
                    {
                        title:'成功励志',
                        subCatId:153,
                        catId:15
                    },
                    {
                        title:'青春文学',
                        subCatId:153,
                        catId:15
                    },
                    {
                        title:'爱情婚姻',
                        subCatId:153,
                        catId:15
                    },
                    {
                        title:'现实百态',
                        subCatId:153,
                        catId:15
                    },
                ]
            },
            {
                title:"军事",
                classify:[
                    {
                        title:'军旅生涯',
                        subCatId:54,
                        catId:6
                    },
                    {
                        title:'军事战争',
                        subCatId:65,
                        catId:6
                    },
                    {
                        title:'战争幻想',
                        subCatId:80,
                        catId:6
                    },
                    {
                        title:'抗战烽火',
                        subCatId:230,
                        catId:6
                    },
                    {
                        title:'谍战特工',
                        subCatId:231,
                        catId:6
                    }
                ]
            },
            {
                title:"悬疑",
                classify:[
                    {
                        title:'诡异悬疑',
                        subCatId:26,
                        catId:10
                    },
                    {
                        title:'奇妙世界',
                        subCatId:35,
                        catId:10
                    },
                    {
                        title:'侦探推理',
                        subCatId:57,
                        catId:10
                    },
                    {
                        title:'谭先生存',
                        subCatId:260,
                        catId:10
                    },
                    {
                        title:'古今奇迹',
                        subCatId:20095,
                        catId:10
                    }
                ]
            },
        ],
        classifyFemaleList:[
            {
                title:"古代言情",
                classify:[
                    {
                        title:'古代情缘',
                        subCatId:801,
                        catId:80
                    },
                    {
                        title:'宫闹宅斗',
                        subCatId:802,
                        catId:80
                    },
                    {
                        title:'经商种田',
                        subCatId:803,
                        catId:80
                    },
                    {
                        title:'穿越奇情',
                        subCatId:806,
                        catId:80
                    },
                    {
                        title:'女尊王朝',
                        subCatId:805,
                        catId:80
                    },
                    {
                        title:'清穿民国',
                        subCatId:30095,
                        catId:80
                    },
                ]
            },
            {
                title:"仙侠奇缘",
                classify:[
                    {
                        title:'武侠情缘',
                        subCatId:810,
                        catId:81
                    },
                    {
                        title:'古典仙侠',
                        subCatId:811,
                        catId:81
                    },
                    {
                        title:'现代修真',
                        subCatId:812,
                        catId:81
                    },
                    {
                        title:'远古洪荒',
                        subCatId:813,
                        catId:81
                    },
                    {
                        title:'仙侣奇缘',
                        subCatId:30093,
                        catId:81
                    }
                ]
            },
            {
                title:"现代言情",
                classify:[
                    {
                        title:'商战职场',
                        subCatId:821,
                        catId:82
                    },
                    {
                        title:'豪门世家',
                        subCatId:822,
                        catId:82
                    },
                    {
                        title:'都市生活',
                        subCatId:823,
                        catId:82
                    },
                    {
                        title:'都市异能',
                        subCatId:827,
                        catId:82
                    },
                    {
                        title:'极道江湖',
                        subCatId:828,
                        catId:82
                    },
                    {
                        title:'民国奇缘',
                        subCatId:829,
                        catId:82
                    }
                ]
            },
            {
                title:"浪漫言情",
                classify:[
                    {
                        title:'青春校园',
                        subCatId:831,
                        catId:83
                    },
                    {
                        title:'青春疼痛',
                        subCatId:832,
                        catId:83
                    },
                    {
                        title:'叛逆成长',
                        subCatId:833,
                        catId:83
                    },
                    {
                        title:'青春纯爱',
                        subCatId:834,
                        catId:83
                    }
                ]
            },
            {
                title:"玄幻言情",
                classify:[
                    {
                        title:'东方玄幻',
                        subCatId:841,
                        catId:84
                    },
                    {
                        title:'异世大陆',
                        subCatId:844,
                        catId:84
                    },
                    {
                        title:'西方奇幻',
                        subCatId:846,
                        catId:84
                    },
                    {
                        title:'远古神话',
                        subCatId:847,
                        catId:84
                    },
                    {
                        title:'魔法幻情',
                        subCatId:849,
                        catId:84
                    }
                ]
            },
            {
                title:"悬疑推理",
                classify:[
                    {
                        title:'推理侦探',
                        subCatId:850,
                        catId:85
                    },
                    {
                        title:'诡秘惊险',
                        subCatId:851,
                        catId:85
                    },
                    {
                        title:'悬疑探险',
                        subCatId:852,
                        catId:85
                    },
                    {
                        title:'奇妙世界',
                        subCatId:853,
                        catId:85
                    },
                    {
                        title:'神秘文化',
                        subCatId:854,
                        catId:85
                    },
                    {
                        title:'幽情奇缘',
                        subCatId:30099,
                        catId:85
                    }
                ]
            },
        ],
        windowHeight:'',
        windowWidth:'',
        gender:'male'
    },
    // 点击男女按钮
    onClick(evt){
        console.log(evt.detail.name);
        if(evt.detail.name==0){
            this.setData({
                gender:'male'
            })
        }
        if(evt.detail.name==1){
            this.setData({
                gender:'female'
            })
        }
        // console.log(this.data.gender);
    },
    // 获取设备宽高
    getSize(){
        wx.getSystemInfo({
            success: res=>{
                this.setData({
                    windowHeight:res.windowHeight,
                    windowWidth:res.windowWidth
                })
            }
        })
    },
    goClassifyRes(options){
        var catId = options.target.dataset.catid;
        var subCatId = options.target.dataset.subcatid;
        // console.log(catId);
        // console.log(subCatId);
        wx.navigateTo({
            url: '../classifyres/classifyres?catId=' + catId + '&subCatId=' + subCatId + '&gender=' + this.data.gender
        })
    },

    /**
     * 生命周期函数--监听页面加载
     */
    onLoad: function (options) {
        this.getSize();
    },

    /**
     * 生命周期函数--监听页面初次渲染完成
     */
    onReady: function () {

    },

    /**
     * 生命周期函数--监听页面显示
     */
    onShow: function () {

    },

    /**
     * 生命周期函数--监听页面隐藏
     */
    onHide: function () {

    },

    /**
     * 生命周期函数--监听页面卸载
     */
    onUnload: function () {

    },

    /**
     * 页面相关事件处理函数--监听用户下拉动作
     */
    onPullDownRefresh: function () {

    },

    /**
     * 页面上拉触底事件的处理函数
     */
    onReachBottom: function () {

    },

    /**
     * 用户点击右上角分享
     */
    onShareAppMessage: function () {

    }
})